// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderBookService_Submit_FullMethodName       = "/orderbook.v1.OrderBookService/Submit"
	OrderBookService_StreamOrders_FullMethodName = "/orderbook.v1.OrderBookService/StreamOrders"
)

// OrderBookServiceClient is the client API for OrderBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderBookService : le service gRPC exposant le moteur.
type OrderBookServiceClient interface {
	// Unaire : équivalent HTTP POST /order (comparable à REST/JSON).
	Submit(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// Streaming bidirectionnel : le client envoie un flux d'ordres,
	// le serveur renvoie un flux de trades en temps réel (multiplexé HTTP/2).
	// C'est l'atout structurel de gRPC — impossible en REST/1.1.
	StreamOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OrderRequest, Trade], error)
}

type orderBookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookServiceClient(cc grpc.ClientConnInterface) OrderBookServiceClient {
	return &orderBookServiceClient{cc}
}

func (c *orderBookServiceClient) Submit(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, OrderBookService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderBookServiceClient) StreamOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OrderRequest, Trade], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderBookService_ServiceDesc.Streams[0], OrderBookService_StreamOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderRequest, Trade]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookService_StreamOrdersClient = grpc.BidiStreamingClient[OrderRequest, Trade]

// OrderBookServiceServer is the server API for OrderBookService service.
// All implementations must embed UnimplementedOrderBookServiceServer
// for forward compatibility.
//
// OrderBookService : le service gRPC exposant le moteur.
type OrderBookServiceServer interface {
	// Unaire : équivalent HTTP POST /order (comparable à REST/JSON).
	Submit(context.Context, *OrderRequest) (*SubmitResponse, error)
	// Streaming bidirectionnel : le client envoie un flux d'ordres,
	// le serveur renvoie un flux de trades en temps réel (multiplexé HTTP/2).
	// C'est l'atout structurel de gRPC — impossible en REST/1.1.
	StreamOrders(grpc.BidiStreamingServer[OrderRequest, Trade]) error
	mustEmbedUnimplementedOrderBookServiceServer()
}

// UnimplementedOrderBookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderBookServiceServer struct{}

func (UnimplementedOrderBookServiceServer) Submit(context.Context, *OrderRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedOrderBookServiceServer) StreamOrders(grpc.BidiStreamingServer[OrderRequest, Trade]) error {
	return status.Error(codes.Unimplemented, "method StreamOrders not implemented")
}
func (UnimplementedOrderBookServiceServer) mustEmbedUnimplementedOrderBookServiceServer() {}
func (UnimplementedOrderBookServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderBookServiceServer will
// result in compilation errors.
type UnsafeOrderBookServiceServer interface {
	mustEmbedUnimplementedOrderBookServiceServer()
}

func RegisterOrderBookServiceServer(s grpc.ServiceRegistrar, srv OrderBookServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderBookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderBookService_ServiceDesc, srv)
}

func _OrderBookService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBookService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServiceServer).Submit(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderBookService_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderBookServiceServer).StreamOrders(&grpc.GenericServerStream[OrderRequest, Trade]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderBookService_StreamOrdersServer = grpc.BidiStreamingServer[OrderRequest, Trade]

// OrderBookService_ServiceDesc is the grpc.ServiceDesc for OrderBookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderBookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderbook.v1.OrderBookService",
	HandlerType: (*OrderBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _OrderBookService_Submit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOrders",
			Handler:       _OrderBookService_StreamOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/order.proto",
}
